POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "size": "medium",
    "toppings": ["cheese", "pepperoni"],
    "quantity": 2
}

GET http://localhost:3000/api/orders

GET http://localhost:3000/api/orders/{orderId}

PUT http://localhost:3000/api/orders/{orderId}
Content-Type: application/json

{
    "size": "large",
    "toppings": ["mushrooms", "olives"],
    "quantity": 3
}

DELETE http://localhost:3000/api/orders/{orderId}

POST http://localhost:3000/api/orders/{orderId}/complete

# to test an endpoint, turn the rest into comments (crtl + / on windows, command + / on mac), and click 'Send Request' at the top of the endpoint.
